language: python
python: 2.7
sudo: false
env:
  matrix:
  - PLONE_VERSION=5.0
install:
  - virtualenv test-env --no-setuptools
  - mkdir -p buildout-cache/downloads
  - test-env/bin/python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -N -q -t 3
script: bin/test
